// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/amazon-bedrock.json" with { type: "json" };
import type { Model } from "../types.ts";

export const AMAZON_BEDROCK_MODELS = values as {
	"amazon.nova-2-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "amazon.nova-2-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"amazon.nova-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "amazon.nova-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"amazon.nova-micro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "amazon.nova-micro-v1:0";
		provider: "amazon-bedrock";
	};
	"amazon.nova-pro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "amazon.nova-pro-v1:0";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-fable-5": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-fable-5";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-fable-5-1": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-fable-5-1";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-4-1-20250805-v1:0": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-4-1-20250805-v1:0";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-4-5-20251101-v1:0": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-4-5-20251101-v1:0";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-4-6-v1": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-4-6-v1";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"apac.amazon.nova-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "apac.amazon.nova-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"apac.amazon.nova-micro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "apac.amazon.nova-micro-v1:0";
		provider: "amazon-bedrock";
	};
	"apac.amazon.nova-pro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "apac.amazon.nova-pro-v1:0";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-opus-4-6-v1": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-opus-4-6-v1";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"au.anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "au.anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"ca.amazon.nova-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "ca.amazon.nova-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"deepseek.v3-v1:0": Model<"bedrock-converse-stream"> & {
		id: "deepseek.v3-v1:0";
		provider: "amazon-bedrock";
	};
	"deepseek.v3.2": Model<"bedrock-converse-stream"> & {
		id: "deepseek.v3.2";
		provider: "amazon-bedrock";
	};
	"eu.amazon.nova-2-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.amazon.nova-2-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.amazon.nova-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.amazon.nova-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.amazon.nova-micro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.amazon.nova-micro-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.amazon.nova-pro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.amazon.nova-pro-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-fable-5": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-fable-5";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-opus-4-5-20251101-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-opus-4-5-20251101-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-opus-4-6-v1": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-opus-4-6-v1";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"eu.anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "eu.anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"eu.mistral.pixtral-large-2502-v1:0": Model<"bedrock-converse-stream"> & {
		id: "eu.mistral.pixtral-large-2502-v1:0";
		provider: "amazon-bedrock";
	};
	"global.amazon.nova-2-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "global.amazon.nova-2-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-fable-5": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-fable-5";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-fable-5-1": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-fable-5-1";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-opus-4-5-20251101-v1:0": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-opus-4-5-20251101-v1:0";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-opus-4-6-v1": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-opus-4-6-v1";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"global.anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "global.anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"global.openai.gpt-5.6-luna": Model<"bedrock-converse-stream"> & {
		id: "global.openai.gpt-5.6-luna";
		provider: "amazon-bedrock";
	};
	"global.openai.gpt-5.6-sol": Model<"bedrock-converse-stream"> & {
		id: "global.openai.gpt-5.6-sol";
		provider: "amazon-bedrock";
	};
	"global.openai.gpt-5.6-terra": Model<"bedrock-converse-stream"> & {
		id: "global.openai.gpt-5.6-terra";
		provider: "amazon-bedrock";
	};
	"global.openai.gpt-6-astra": Model<"bedrock-converse-stream"> & {
		id: "global.openai.gpt-6-astra";
		provider: "amazon-bedrock";
	};
	"global.xai.grok-4.6": Model<"bedrock-converse-stream"> & {
		id: "global.xai.grok-4.6";
		provider: "amazon-bedrock";
	};
	"google.gemma-4-26b-a4b": Model<"bedrock-converse-stream"> & {
		id: "google.gemma-4-26b-a4b";
		provider: "amazon-bedrock";
	};
	"google.gemma-4-31b": Model<"bedrock-converse-stream"> & {
		id: "google.gemma-4-31b";
		provider: "amazon-bedrock";
	};
	"google.gemma-4-e2b": Model<"bedrock-converse-stream"> & {
		id: "google.gemma-4-e2b";
		provider: "amazon-bedrock";
	};
	"in.openai.gpt-5.6-luna": Model<"bedrock-converse-stream"> & {
		id: "in.openai.gpt-5.6-luna";
		provider: "amazon-bedrock";
	};
	"in.openai.gpt-5.6-terra": Model<"bedrock-converse-stream"> & {
		id: "in.openai.gpt-5.6-terra";
		provider: "amazon-bedrock";
	};
	"jp.amazon.nova-2-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "jp.amazon.nova-2-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"jp.anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "jp.anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"meta.llama3-1-70b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "meta.llama3-1-70b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"meta.llama3-1-8b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "meta.llama3-1-8b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"meta.llama3-3-70b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "meta.llama3-3-70b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"meta.llama4-maverick-17b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "meta.llama4-maverick-17b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"meta.llama4-scout-17b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "meta.llama4-scout-17b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"minimax.minimax-m2": Model<"bedrock-converse-stream"> & {
		id: "minimax.minimax-m2";
		provider: "amazon-bedrock";
	};
	"minimax.minimax-m2.1": Model<"bedrock-converse-stream"> & {
		id: "minimax.minimax-m2.1";
		provider: "amazon-bedrock";
	};
	"minimax.minimax-m2.5": Model<"bedrock-converse-stream"> & {
		id: "minimax.minimax-m2.5";
		provider: "amazon-bedrock";
	};
	"mistral.devstral-2-123b": Model<"bedrock-converse-stream"> & {
		id: "mistral.devstral-2-123b";
		provider: "amazon-bedrock";
	};
	"mistral.magistral-small-2509": Model<"bedrock-converse-stream"> & {
		id: "mistral.magistral-small-2509";
		provider: "amazon-bedrock";
	};
	"mistral.ministral-3-14b-instruct": Model<"bedrock-converse-stream"> & {
		id: "mistral.ministral-3-14b-instruct";
		provider: "amazon-bedrock";
	};
	"mistral.ministral-3-3b-instruct": Model<"bedrock-converse-stream"> & {
		id: "mistral.ministral-3-3b-instruct";
		provider: "amazon-bedrock";
	};
	"mistral.ministral-3-8b-instruct": Model<"bedrock-converse-stream"> & {
		id: "mistral.ministral-3-8b-instruct";
		provider: "amazon-bedrock";
	};
	"mistral.mistral-large-3-675b-instruct": Model<"bedrock-converse-stream"> & {
		id: "mistral.mistral-large-3-675b-instruct";
		provider: "amazon-bedrock";
	};
	"mistral.pixtral-large-2502-v1:0": Model<"bedrock-converse-stream"> & {
		id: "mistral.pixtral-large-2502-v1:0";
		provider: "amazon-bedrock";
	};
	"mistral.voxtral-mini-3b-2507": Model<"bedrock-converse-stream"> & {
		id: "mistral.voxtral-mini-3b-2507";
		provider: "amazon-bedrock";
	};
	"mistral.voxtral-small-24b-2507": Model<"bedrock-converse-stream"> & {
		id: "mistral.voxtral-small-24b-2507";
		provider: "amazon-bedrock";
	};
	"moonshot.kimi-k2-thinking": Model<"bedrock-converse-stream"> & {
		id: "moonshot.kimi-k2-thinking";
		provider: "amazon-bedrock";
	};
	"moonshotai.kimi-k2.5": Model<"bedrock-converse-stream"> & {
		id: "moonshotai.kimi-k2.5";
		provider: "amazon-bedrock";
	};
	"nvidia.nemotron-nano-12b-v2": Model<"bedrock-converse-stream"> & {
		id: "nvidia.nemotron-nano-12b-v2";
		provider: "amazon-bedrock";
	};
	"nvidia.nemotron-nano-3-30b": Model<"bedrock-converse-stream"> & {
		id: "nvidia.nemotron-nano-3-30b";
		provider: "amazon-bedrock";
	};
	"nvidia.nemotron-nano-9b-v2": Model<"bedrock-converse-stream"> & {
		id: "nvidia.nemotron-nano-9b-v2";
		provider: "amazon-bedrock";
	};
	"nvidia.nemotron-super-3-120b": Model<"bedrock-converse-stream"> & {
		id: "nvidia.nemotron-super-3-120b";
		provider: "amazon-bedrock";
	};
	"openai.gpt-5.4": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-5.4";
		provider: "amazon-bedrock";
	};
	"openai.gpt-5.5": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-5.5";
		provider: "amazon-bedrock";
	};
	"openai.gpt-5.6-luna": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-5.6-luna";
		provider: "amazon-bedrock";
	};
	"openai.gpt-5.6-sol": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-5.6-sol";
		provider: "amazon-bedrock";
	};
	"openai.gpt-5.6-terra": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-5.6-terra";
		provider: "amazon-bedrock";
	};
	"openai.gpt-6-astra": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-6-astra";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-120b": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-120b";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-120b-1:0": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-120b-1:0";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-20b": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-20b";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-20b-1:0": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-20b-1:0";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-safeguard-120b": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-safeguard-120b";
		provider: "amazon-bedrock";
	};
	"openai.gpt-oss-safeguard-20b": Model<"bedrock-converse-stream"> & {
		id: "openai.gpt-oss-safeguard-20b";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-235b-a22b-2507-v1:0": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-235b-a22b-2507-v1:0";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-32b-v1:0": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-32b-v1:0";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-coder-30b-a3b-v1:0": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-coder-30b-a3b-v1:0";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-coder-480b-a35b-v1:0": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-coder-480b-a35b-v1:0";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-coder-next": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-coder-next";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-next-80b-a3b": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-next-80b-a3b";
		provider: "amazon-bedrock";
	};
	"qwen.qwen3-vl-235b-a22b": Model<"bedrock-converse-stream"> & {
		id: "qwen.qwen3-vl-235b-a22b";
		provider: "amazon-bedrock";
	};
	"us-gov.openai.gpt-oss-120b-1:0": Model<"bedrock-converse-stream"> & {
		id: "us-gov.openai.gpt-oss-120b-1:0";
		provider: "amazon-bedrock";
	};
	"us-gov.openai.gpt-oss-20b-1:0": Model<"bedrock-converse-stream"> & {
		id: "us-gov.openai.gpt-oss-20b-1:0";
		provider: "amazon-bedrock";
	};
	"us.amazon.nova-2-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.amazon.nova-2-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"us.amazon.nova-lite-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.amazon.nova-lite-v1:0";
		provider: "amazon-bedrock";
	};
	"us.amazon.nova-micro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.amazon.nova-micro-v1:0";
		provider: "amazon-bedrock";
	};
	"us.amazon.nova-premier-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.amazon.nova-premier-v1:0";
		provider: "amazon-bedrock";
	};
	"us.amazon.nova-pro-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.amazon.nova-pro-v1:0";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-fable-5": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-fable-5";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-fable-5-1": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-fable-5-1";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-haiku-4-5-20251001-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-haiku-4-5-20251001-v1:0";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-4-1-20250805-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-4-1-20250805-v1:0";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-4-5-20251101-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-4-5-20251101-v1:0";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-4-6-v1": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-4-6-v1";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-4-7": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-4-7";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-4-8": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-4-8";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-opus-5": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-opus-5";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-sonnet-4-5-20250929-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-sonnet-4-6": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-sonnet-4-6";
		provider: "amazon-bedrock";
	};
	"us.anthropic.claude-sonnet-5": Model<"bedrock-converse-stream"> & {
		id: "us.anthropic.claude-sonnet-5";
		provider: "amazon-bedrock";
	};
	"us.meta.llama3-1-70b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.meta.llama3-1-70b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"us.meta.llama3-1-8b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.meta.llama3-1-8b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"us.meta.llama3-3-70b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.meta.llama3-3-70b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"us.meta.llama4-maverick-17b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.meta.llama4-maverick-17b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"us.meta.llama4-scout-17b-instruct-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.meta.llama4-scout-17b-instruct-v1:0";
		provider: "amazon-bedrock";
	};
	"us.mistral.pixtral-large-2502-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.mistral.pixtral-large-2502-v1:0";
		provider: "amazon-bedrock";
	};
	"us.openai.gpt-5.6-luna": Model<"bedrock-converse-stream"> & {
		id: "us.openai.gpt-5.6-luna";
		provider: "amazon-bedrock";
	};
	"us.openai.gpt-5.6-sol": Model<"bedrock-converse-stream"> & {
		id: "us.openai.gpt-5.6-sol";
		provider: "amazon-bedrock";
	};
	"us.openai.gpt-5.6-terra": Model<"bedrock-converse-stream"> & {
		id: "us.openai.gpt-5.6-terra";
		provider: "amazon-bedrock";
	};
	"us.openai.gpt-6-astra": Model<"bedrock-converse-stream"> & {
		id: "us.openai.gpt-6-astra";
		provider: "amazon-bedrock";
	};
	"us.writer.palmyra-x4-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.writer.palmyra-x4-v1:0";
		provider: "amazon-bedrock";
	};
	"us.writer.palmyra-x5-v1:0": Model<"bedrock-converse-stream"> & {
		id: "us.writer.palmyra-x5-v1:0";
		provider: "amazon-bedrock";
	};
	"us.xai.grok-4.6": Model<"bedrock-converse-stream"> & {
		id: "us.xai.grok-4.6";
		provider: "amazon-bedrock";
	};
	"writer.palmyra-x4-v1:0": Model<"bedrock-converse-stream"> & {
		id: "writer.palmyra-x4-v1:0";
		provider: "amazon-bedrock";
	};
	"writer.palmyra-x5-v1:0": Model<"bedrock-converse-stream"> & {
		id: "writer.palmyra-x5-v1:0";
		provider: "amazon-bedrock";
	};
	"xai.grok-4.3": Model<"bedrock-converse-stream"> & {
		id: "xai.grok-4.3";
		provider: "amazon-bedrock";
	};
	"xai.grok-4.6": Model<"bedrock-converse-stream"> & {
		id: "xai.grok-4.6";
		provider: "amazon-bedrock";
	};
	"zai.glm-4.7": Model<"bedrock-converse-stream"> & {
		id: "zai.glm-4.7";
		provider: "amazon-bedrock";
	};
	"zai.glm-4.7-flash": Model<"bedrock-converse-stream"> & {
		id: "zai.glm-4.7-flash";
		provider: "amazon-bedrock";
	};
	"zai.glm-5": Model<"bedrock-converse-stream"> & {
		id: "zai.glm-5";
		provider: "amazon-bedrock";
	};
};
