// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cerebras.json" with { type: "json" };
import type { Model } from "../types.ts";

export const CEREBRAS_MODELS = values as {
	"gpt-oss-120b": Model<"openai-completions"> & {
		id: "gpt-oss-120b";
		provider: "cerebras";
	};
	"qwen-3.8-27b": Model<"openai-completions"> & {
		id: "qwen-3.8-27b";
		provider: "cerebras";
	};
};
