// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import type { Model } from "../types.ts";

export const FIREWORKS_MODELS = values as {
	"accounts/fireworks/models/deepseek-v4p1-flash": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/deepseek-v4p1-flash";
		provider: "fireworks";
	};
	"accounts/fireworks/models/ember-1": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/ember-1";
		provider: "fireworks";
	};
	"accounts/fireworks/models/glm-5p3": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/glm-5p3";
		provider: "fireworks";
	};
	"accounts/fireworks/models/glm-5p3-flash": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/glm-5p3-flash";
		provider: "fireworks";
	};
	"accounts/fireworks/models/gpt-oss-120b": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/gpt-oss-120b";
		provider: "fireworks";
	};
	"accounts/fireworks/models/inkling": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/inkling";
		provider: "fireworks";
	};
	"accounts/fireworks/models/kimi-k3": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/kimi-k3";
		provider: "fireworks";
	};
	"accounts/fireworks/models/minimax-m3": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/minimax-m3";
		provider: "fireworks";
	};
	"accounts/fireworks/models/nemotron-3-ultra-nvfp4": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/nemotron-3-ultra-nvfp4";
		provider: "fireworks";
	};
	"accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b";
		provider: "fireworks";
	};
	"accounts/fireworks/models/qwen3p8-2p4t-a95b": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/qwen3p8-2p4t-a95b";
		provider: "fireworks";
	};
	"accounts/fireworks/models/qwen3p8-max": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/qwen3p8-max";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/deepseek-flash-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/deepseek-flash-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-5p3-fast": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/glm-5p3-fast";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-fast-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/glm-fast-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-flash-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/glm-flash-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/glm-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-fast-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-fast-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-k3-fast": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-k3-fast";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/minimax-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/minimax-latest";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/qwen-max-latest": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/qwen-max-latest";
		provider: "fireworks";
	};
};
