// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/moonshotai-cn.json" with { type: "json" };
import type { Model } from "../types.ts";

export const MOONSHOTAI_CN_MODELS = values as {
	"kimi-k2.6": Model<"openai-completions"> & {
		id: "kimi-k2.6";
		provider: "moonshotai-cn";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "moonshotai-cn";
	};
	"kimi-k2.7-code-highspeed": Model<"openai-completions"> & {
		id: "kimi-k2.7-code-highspeed";
		provider: "moonshotai-cn";
	};
	"kimi-k3": Model<"openai-completions"> & {
		id: "kimi-k3";
		provider: "moonshotai-cn";
	};
};
