// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/nvidia.json" with { type: "json" };
import type { Model } from "../types.ts";

export const NVIDIA_MODELS = values as {
	"deepseek-ai/deepseek-v4-flash-0731": Model<"openai-completions"> & {
		id: "deepseek-ai/deepseek-v4-flash-0731";
		provider: "nvidia";
	};
	"google/gemma-3-12b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-12b-it";
		provider: "nvidia";
	};
	"google/gemma-3-4b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-4b-it";
		provider: "nvidia";
	};
	"meta/llama-3.2-11b-vision-instruct": Model<"openai-completions"> & {
		id: "meta/llama-3.2-11b-vision-instruct";
		provider: "nvidia";
	};
	"meta/llama-3.2-90b-vision-instruct": Model<"openai-completions"> & {
		id: "meta/llama-3.2-90b-vision-instruct";
		provider: "nvidia";
	};
	"meta/muse-glimmer-30b": Model<"openai-completions"> & {
		id: "meta/muse-glimmer-30b";
		provider: "nvidia";
	};
	"mistralai/mistral-7b-instruct-v0.3": Model<"openai-completions"> & {
		id: "mistralai/mistral-7b-instruct-v0.3";
		provider: "nvidia";
	};
	"moonshotai/kimi-k2.6": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.6";
		provider: "nvidia";
	};
	"moonshotai/kimi-k3": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3";
		provider: "nvidia";
	};
	"nvidia/cosmos-reason2-8b": Model<"openai-completions"> & {
		id: "nvidia/cosmos-reason2-8b";
		provider: "nvidia";
	};
	"nvidia/llama-3.1-nemotron-70b-instruct": Model<"openai-completions"> & {
		id: "nvidia/llama-3.1-nemotron-70b-instruct";
		provider: "nvidia";
	};
	"nvidia/llama-3.1-nemotron-ultra-253b-v1": Model<"openai-completions"> & {
		id: "nvidia/llama-3.1-nemotron-ultra-253b-v1";
		provider: "nvidia";
	};
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning";
		provider: "nvidia";
	};
	"nvidia/nemotron-3-super-120b-a12b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-super-120b-a12b";
		provider: "nvidia";
	};
	"nvidia/nemotron-3-ultra-550b-a55b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-ultra-550b-a55b";
		provider: "nvidia";
	};
	"nvidia/nemotron-3.5-lightning-30b-a3b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3.5-lightning-30b-a3b";
		provider: "nvidia";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "nvidia";
	};
	"poolside/laguna-xs-2.1": Model<"openai-completions"> & {
		id: "poolside/laguna-xs-2.1";
		provider: "nvidia";
	};
	"z-ai/glm-5.3-flash": Model<"openai-completions"> & {
		id: "z-ai/glm-5.3-flash";
		provider: "nvidia";
	};
};
