// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai-coding-cn.json" with { type: "json" };
import type { Model } from "../types.ts";

export const ZAI_CODING_CN_MODELS = values as {
	"glm-4.7": Model<"openai-completions"> & {
		id: "glm-4.7";
		provider: "zai-coding-cn";
	};
	"glm-5-turbo": Model<"openai-completions"> & {
		id: "glm-5-turbo";
		provider: "zai-coding-cn";
	};
	"glm-5.2": Model<"openai-completions"> & {
		id: "glm-5.2";
		provider: "zai-coding-cn";
	};
	"glm-5.2-highspeed": Model<"openai-completions"> & {
		id: "glm-5.2-highspeed";
		provider: "zai-coding-cn";
	};
	"glm-5.3": Model<"openai-completions"> & {
		id: "glm-5.3";
		provider: "zai-coding-cn";
	};
	"glm-5.3-flash": Model<"openai-completions"> & {
		id: "glm-5.3-flash";
		provider: "zai-coding-cn";
	};
	"glm-5.3-highspeed": Model<"openai-completions"> & {
		id: "glm-5.3-highspeed";
		provider: "zai-coding-cn";
	};
};
